# https://docs.travis-ci.com/user/languages/php/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/build-environment-updates/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/deployment/releases/
# https://docs.travis-ci.com/user/deployment/pages/

language: php
dist: xenial
group: edge
php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

cache:
  directories:
    - bin
    - vendor

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

before_script:
  - 'travis_retry composer self-update'
  - 'travis_retry composer install --ignore-platform-reqs --no-interaction --prefer-source -oa'
  - 'wget https://scrutinizer-ci.com/ocular.phar'
  - 'phpenv rehash'

script:
  - 'mkdir -p tests/report'
  - 'php bin/phpunit -c phpunit.xml.dist'

# https://github.com/php-coveralls/php-coveralls#travis-ci
# https://scrutinizer-ci.com/docs/tools/external-code-coverage/
after_success:
  - 'travis_retry php bin/php-coveralls -v'
  - 'travis_retry php ocular.phar code-coverage:upload --format=php-clover tests/report/clover.xml'
  - 'curl -o http://get.sensiolabs.org/sami.phar sami.phar'
  # - 'git reset --hard HEAD'
  # - 'travis_retry php sami.phar update --force docs/sami-config.php'

notifications:
  email:
    - 'ryan@ryanparman.com'
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/89f22ac7aa288b13852c'
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# https://docs.travis-ci.com/user/deployment/script/
# https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example
# deploy:
#   - provider: script
#     script: make push-travis
#     on:
#       branch: master

env:
  global:
    secure: b2DFCIHGLW72GKoDclsIpEIDF7jvVNQUUXIVEmpD5+6cwko3dXVE+3iRD7LN7GumUUXjt/B3GsUGOBxz2KLqBLV9znLg/6JHLxcRSBN93obXYYqSq2llfjO5IJzXHzXmwddgXyG9wlmxfq7AKYdL5sxDB+alu+q3ONCnNX/hqVQ59hVJSjA3ivLAO9i/sttZkOlvG2fjgUF27IIRvn5DXRjqurU+PDxnPsMVKHgMTTx1Riu+taWpskfzHsD9QXFu2fTeyJU89tMCiUvvZrpuFyYabFteF9JGCKf75nisQDg/1geuwxGcW4Id8fvtmkdlvn/GPVtP3PAcrrDdgqypg7GcHupnK7hOM/4yZ9gSFFZfXMt6o/51XfHt2Lj4DqsF2jjokqLmLMDL+3X7CSBht2R4F4vBkIM/R/k4VRpJtcp2O+V6va5YPZULhl5LvMrIKTBhlGO+dVBVpKQ/TNI53KqV5eDVaDPLUgeKCqeKnf4D1kzfeMOdHyLCI5qEnsX+9faaPDEb0mS7u3RuN5UUqTkbI+xpoDkYQcf3cfa9cbIwg7bjtsxH17EPtCILsq4HALdnMHhqlJX0+VX1c31S3kNR8RTADSet3IUVOEYLOhLvugE6hlY3Wu7lqP7+n6/pM4gKCH+Lyy9JMKS57JRnYOVqkpAEA4NdcWM0FAddVLE=
